version: '2'
services:
  luna:
    container_name: luna-backend
    restart: always
    build: .
    ports:
      - '80:5600'
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
